services:
  - type: web
    name: rms-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python train.py"
    startCommand: "gunicorn server:app"
    plan: free
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
